version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://root:root@postgres/my_collections
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_collections
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  postgres_data:
